[package]
name = "paro"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
clap = { version = "3.2.16", features = ["derive"] }
config = "0.13.2"
serde = { version = "1.0.142", features = ["derive"]}
