name: release
on:
  push:
    # Enable when testing release infrastructure on a branch.
    branches:
    - ci/test
    tags:
    - "[0-9]+.[0-9]+.[0-9]+"

jobs:
  build:
    strategy:
      matrix:
        include:
          - os: ubuntu-20.04
            target: x86_64-unknown-linux-gnu
            code-target: linux-x64
          - os: ubuntu-20.04
            target: aarch64-unknown-linux-gnu
            code-target: linux-arm64
          - os: macos-11
            target: x86_64-apple-darwin
            code-target: darwin-x64
          - os: macos-11
            target: aarch64-apple-darwin
            code-target: darwin-arm64

    name: dist (${{ matrix.target }})
    runs-on: ${{ matrix.os }}

    env:
      RA_TARGET: ${{ matrix.target }}

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          fetch-depth: ${{ env.FETCH_DEPTH }}

      - name: Get latest tag
        id: latest-tag
        uses: WyriHaximus/github-action-get-previous-tag@v1
        with:
          fallback: 0.0.1 # Optional fallback tag to use when no tag can be found

      - name: Install Rust toolchain
        run: |
          rustup update --no-self-update stable
          rustup target add ${{ matrix.target }}
          rustup component add rust-src

      - name: Set version
        run: sed -i -e 's/^version = .*/version = "${{ steps.latest-tag.outputs.tag }}"/' Cargo.toml

      - name: Install Cross
        run: cargo install cross

      - name: Cross Build
        run: cross build --release --target=${{ matrix.target }}

      - name: Upload artifacts
        uses: actions/upload-artifact@v1
        with:
          name: paro-${{ steps.latest-tag.outputs.tag }}-${{ matrix.target }}
          path: ./target/${{ matrix.target }}/release/paro

  release:
    runs-on: ubuntu-latest
    name: Download artifacts
    needs: [build]

    steps:
      - name: Download artifacts
        uses: actions/download-artifact@v3

      - name: Display structure of downloaded files
        run: ls -R

      #- name: Release to GiHub
        #uses: softprops/action-gh-release@v1
        #with:
          #files: "*.zip"
          #draft: true
        #env:
          #GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
